<?php

$departments = <<<DEP
<section class="esg-list-group">
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ACCT" title="Accounting" id="catalog-subject-ACCT">Accounting</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ABS" title="Acup Basic Science" id="catalog-subject-ABS">Acup Basic Science</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ABM" title="Acup Botanical Medicine" id="catalog-subject-ABM">Acup Botanical Medicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ACS" title="Acup Clinical Services" id="catalog-subject-ACS">Acup Clinical Services</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=AHM" title="Acup Herbal Med Thry" id="catalog-subject-AHM">Acup Herbal Med Thry</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ANT" title="Acup Nutrition" id="catalog-subject-ANT">Acup Nutrition</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=APT" title="Acup Pract &amp; Tech" id="catalog-subject-APT">Acup Pract &amp; Tech</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=APP" title="Acup Principles &amp; Practice" id="catalog-subject-APP">Acup Principles &amp; Practice</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=APS" title="Acup Psyc" id="catalog-subject-APS">Acup Psyc</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=AN" title="Anatomy" id="catalog-subject-AN">Anatomy</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=APM" title="Applied Music" id="catalog-subject-APM">Applied Music</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ARAB" title="Arabic" id="catalog-subject-ARAB">Arabic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ARABC" title="Arabic Language" id="catalog-subject-ARABC">Arabic Language</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ADSN" title="Art &amp; Design" id="catalog-subject-ADSN">Art &amp; Design</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ARED" title="Art Education" id="catalog-subject-ARED">Art Education</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ARSC" title="Arts &amp; Sciences" id="catalog-subject-ARSC">Arts &amp; Sciences</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ACH" title="Asian/Chinese Herbology" id="catalog-subject-ACH">Asian/Chinese Herbology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=AC" title="Assoc Clin Studies" id="catalog-subject-AC">Assoc Clin Studies</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NBS" title="Basic Studies" id="catalog-subject-NBS">Basic Studies</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BC" title="Biochemistry- Chiropractic" id="catalog-subject-BC">Biochemistry- Chiropractic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BIOL" title="Biology" id="catalog-subject-BIOL">Biology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BMEG" title="Biomedical Engineering" id="catalog-subject-BMEG">Biomedical Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NBM" title="Botanical Medicine" id="catalog-subject-NBM">Botanical Medicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BUAD" title="Business Administration" id="catalog-subject-BUAD">Business Administration</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BAI" title="Business Analytics &amp; Intellige" id="catalog-subject-BAI">Business Analytics &amp; Intellige</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BUCP" title="Business Capstone" id="catalog-subject-BUCP">Business Capstone</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BLAW" title="Business Law" id="catalog-subject-BLAW">Business Law</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=BP" title="Business Procedures- Chiroprac" id="catalog-subject-BP">Business Procedures- Chiroprac</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CAPS" title="Capstone" id="catalog-subject-CAPS">Capstone</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CHEM" title="Chemistry" id="catalog-subject-CHEM">Chemistry</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CHIN" title="Chinese" id="catalog-subject-CHIN">Chinese</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ACC" title="Chinese Herbal Clinic" id="catalog-subject-ACC">Chinese Herbal Clinic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CHIRO" title="Chiropractic" id="catalog-subject-CHIRO">Chiropractic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PR" title="Chiropractic Principles" id="catalog-subject-PR">Chiropractic Principles</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=TE" title="Chiropractic Skills/Technique" id="catalog-subject-TE">Chiropractic Skills/Technique</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CINE" title="Cinema" id="catalog-subject-CINE">Cinema</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CIHT" title="Cinema History and Theory" id="catalog-subject-CIHT">Cinema History and Theory</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NCE" title="Clinical Education" id="catalog-subject-NCE">Clinical Education</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NNT" title="Clinical Nutrition" id="catalog-subject-NNT">Clinical Nutrition</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CN" title="Clinical Nutrition- Chiroprac" id="catalog-subject-CN">Clinical Nutrition- Chiroprac</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PS" title="Clinical Psychology- Chiro" id="catalog-subject-PS">Clinical Psychology- Chiro</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NCS" title="Clinical Sciences" id="catalog-subject-NCS">Clinical Sciences</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CL" title="Clinical Services" id="catalog-subject-CL">Clinical Services</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CS" title="Clinical Services- Chiroprac" id="catalog-subject-CS">Clinical Services- Chiroprac</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CBIT" title="Cntr Busn Info Tech Program" id="catalog-subject-CBIT">Cntr Busn Info Tech Program</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=COMM" title="Communications" id="catalog-subject-COMM">Communications</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CAIS" title="Comp Application/Info Sytems" id="catalog-subject-CAIS">Comp Application/Info Sytems</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CPEG" title="Computer Engineering" id="catalog-subject-CPEG">Computer Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CPSC" title="Computer Science" id="catalog-subject-CPSC">Computer Science</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=COUN" title="Counseling" id="catalog-subject-COUN">Counseling</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CPET" title="Cptr Engr Technology" id="catalog-subject-CPET">Cptr Engr Technology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CJHS" title="Criminal Justice" id="catalog-subject-CJHS">Criminal Justice</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DHYG" title="Dental Hygiene" id="catalog-subject-DHYG">Dental Hygiene</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DNUTR" title="Dental Hygiene Nutrition" id="catalog-subject-DNUTR">Dental Hygiene Nutrition</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DESN" title="Design" id="catalog-subject-DESN">Design</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DSNMG" title="Design Management" id="catalog-subject-DSNMG">Design Management</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DX" title="Diagnosis" id="catalog-subject-DX">Diagnosis</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DD" title="Differential Diagnosis" id="catalog-subject-DD">Differential Diagnosis</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DMCM" title="Digitial Marketing Comm" id="catalog-subject-DMCM">Digitial Marketing Comm</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=EAPRS" title="East Asian &amp; Pacific Rim Stud" id="catalog-subject-EAPRS">East Asian &amp; Pacific Rim Stud</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ECON" title="Economics" id="catalog-subject-ECON">Economics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=EDUC" title="Education" id="catalog-subject-EDUC">Education</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=EDMM" title="Education Mod Map" id="catalog-subject-EDMM">Education Mod Map</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=EDLD" title="Educational Leadership" id="catalog-subject-EDLD">Educational Leadership</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=EDIT" title="Education-Instructional Tech" id="catalog-subject-EDIT">Education-Instructional Tech</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ELEG" title="Electrical Engineering" id="catalog-subject-ELEG">Electrical Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ED" title="Electrodiagnosis" id="catalog-subject-ED">Electrodiagnosis</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ER" title="Emergency Procedures" id="catalog-subject-ER">Emergency Procedures</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ENGR" title="Engineering" id="catalog-subject-ENGR">Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ESL" title="Engl As Second Lang" id="catalog-subject-ESL">Engl As Second Lang</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ENGL" title="English" id="catalog-subject-ENGL">English</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ELI" title="English Lang Institute" id="catalog-subject-ELI">English Lang Institute</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=FM" title="Fashion Merchandising" id="catalog-subject-FM">Fashion Merchandising</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=FIN" title="Finance" id="catalog-subject-FIN">Finance</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=FA" title="Fine Arts" id="catalog-subject-FA">Fine Arts</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=FYE" title="First Year Experience" id="catalog-subject-FYE">First Year Experience</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=FYS" title="First Year Seminar" id="catalog-subject-FYS">First Year Seminar</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=FREN" title="French" id="catalog-subject-FREN">French</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GNST" title="General Studies" id="catalog-subject-GNST">General Studies</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GEOL" title="Geology" id="catalog-subject-GEOL">Geology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GERM" title="German" id="catalog-subject-GERM">German</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GERO" title="Gerontology" id="catalog-subject-GERO">Gerontology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GMCS" title="Global Communication" id="catalog-subject-GMCS">Global Communication</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GLDP" title="Global Development &amp; Peace" id="catalog-subject-GLDP">Global Development &amp; Peace</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=GDSN" title="Graphic Design" id="catalog-subject-GDSN">Graphic Design</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HSCI" title="Health Science" id="catalog-subject-HSCI">Health Science</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HLSC" title="Health Science Doctoral" id="catalog-subject-HLSC">Health Science Doctoral</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HLAD" title="Healthcare Administration" id="catalog-subject-HLAD">Healthcare Administration</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HIST" title="History" id="catalog-subject-HIST">History</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NHM" title="Homeopathic Medicine" id="catalog-subject-NHM">Homeopathic Medicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HONT" title="Honors Curriculum Track" id="catalog-subject-HONT">Honors Curriculum Track</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HONR" title="Honors Program" id="catalog-subject-HONR">Honors Program</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HRAD" title="Human Resource Administration" id="catalog-subject-HRAD">Human Resource Administration</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HUSV" title="Human Services" id="catalog-subject-HUSV">Human Services</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=HUM" title="Humanities" id="catalog-subject-HUM">Humanities</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ILLUS" title="Illustration" id="catalog-subject-ILLUS">Illustration</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=IDDSN" title="Industrial Design" id="catalog-subject-IDDSN">Industrial Design</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ITKM" title="Information Tech Mgmt" id="catalog-subject-ITKM">Information Tech Mgmt</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=INTST" title="Integrated Studies" id="catalog-subject-INTST">Integrated Studies</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ITDSN" title="Interior Design" id="catalog-subject-ITDSN">Interior Design</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=INTLBU" title="International Business" id="catalog-subject-INTLBU">International Business</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=IPED" title="Intl Pol Econ &amp; Diplomacy" id="catalog-subject-IPED">Intl Pol Econ &amp; Diplomacy</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=JAPN" title="Japanese" id="catalog-subject-JAPN">Japanese</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=KORN" title="Korean" id="catalog-subject-KORN">Korean</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=LD" title="Learning Development" id="catalog-subject-LD">Learning Development</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=LAS" title="Legal Assistant Studies" id="catalog-subject-LAS">Legal Assistant Studies</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=LART" title="Liberal Arts Topics" id="catalog-subject-LART">Liberal Arts Topics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MSPA" title="M.S. Physician Assistant" id="catalog-subject-MSPA">M.S. Physician Assistant</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MGMT" title="Management &amp; Ind Relations" id="catalog-subject-MGMT">Management &amp; Ind Relations</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MGEG" title="Management Engineering" id="catalog-subject-MGEG">Management Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MIS" title="Management Information Systems" id="catalog-subject-MIS">Management Information Systems</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MGSC" title="Management Science" id="catalog-subject-MGSC">Management Science</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MGTIR" title="Management/Industrial Relation" id="catalog-subject-MGTIR">Management/Industrial Relation</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MKTG" title="Marketing" id="catalog-subject-MKTG">Marketing</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MARTS" title="Martial Arts" id="catalog-subject-MARTS">Martial Arts</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MCOM" title="Mass Communications" id="catalog-subject-MCOM">Mass Communications</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MPH" title="Master of Public Health" id="catalog-subject-MPH">Master of Public Health</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MATH" title="Mathematics" id="catalog-subject-MATH">Mathematics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MEEG" title="Mechanical Engineering" id="catalog-subject-MEEG">Mechanical Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MLSC" title="Medical Laboratory Sciences" id="catalog-subject-MLSC">Medical Laboratory Sciences</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MEDTECH" title="Medical Technology" id="catalog-subject-MEDTECH">Medical Technology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MDTCH" title="Medical Technology" id="catalog-subject-MDTCH">Medical Technology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ITIS" title="Mgmt Info Systems" id="catalog-subject-ITIS">Mgmt Info Systems</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MB" title="Microbiology and Public Health" id="catalog-subject-MB">Microbiology and Public Health</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=LANG" title="Modern Language" id="catalog-subject-LANG">Modern Language</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=AMR" title="Movemnt &amp; Respiratn Stds" id="catalog-subject-AMR">Movemnt &amp; Respiratn Stds</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MUSC" title="Music" id="catalog-subject-MUSC">Music</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=MSED" title="Music Education" id="catalog-subject-MSED">Music Education</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NTCM" title="Nat Trad Chinese Medicine" id="catalog-subject-NTCM">Nat Trad Chinese Medicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NPS" title="Naturopathic Med Psychology" id="catalog-subject-NPS">Naturopathic Med Psychology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NOB" title="Naturopathic Obstetrics" id="catalog-subject-NOB">Naturopathic Obstetrics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NS" title="Neuroscience" id="catalog-subject-NS">Neuroscience</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NURS" title="Nursing" id="catalog-subject-NURS">Nursing</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NUTR" title="Nutrition" id="catalog-subject-NUTR">Nutrition</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ORLD" title="Organizational Leadership" id="catalog-subject-ORLD">Organizational Leadership</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NOM" title="Oriental Medicine" id="catalog-subject-NOM">Oriental Medicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=ATD" title="Oriental Thry,Diagn &amp; Appl" id="catalog-subject-ATD">Oriental Thry,Diagn &amp; Appl</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PA" title="Pathology" id="catalog-subject-PA">Pathology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=CPSE" title="Phd Comp Sci &amp; Engr" id="catalog-subject-CPSE">Phd Comp Sci &amp; Engr</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PHIL" title="Philosophy" id="catalog-subject-PHIL">Philosophy</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PHTO" title="Photography" id="catalog-subject-PHTO">Photography</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NPM" title="Physical Medicine" id="catalog-subject-NPM">Physical Medicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PHYS" title="Physics" id="catalog-subject-PHYS">Physics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PT" title="Physiological Therapeutics" id="catalog-subject-PT">Physiological Therapeutics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PH" title="Physiology- Chiropractic" id="catalog-subject-PH">Physiology- Chiropractic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PSCI" title="Political Science" id="catalog-subject-PSCI">Political Science</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PGCH" title="Post Graduate Chiropractic" id="catalog-subject-PGCH">Post Graduate Chiropractic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PG" title="Post-Graduate Chiro" id="catalog-subject-PG">Post-Graduate Chiro</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PGDH" title="Post-Graduate Dental Hyg" id="catalog-subject-PGDH">Post-Graduate Dental Hyg</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NNP" title="Practice Organ Systems" id="catalog-subject-NNP">Practice Organ Systems</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PP" title="Principles and Practice- Chiro" id="catalog-subject-PP">Principles and Practice- Chiro</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NPP" title="Principles and Practices" id="catalog-subject-NPP">Principles and Practices</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PDGM" title="Prof Dev General Management" id="catalog-subject-PDGM">Prof Dev General Management</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PDEN" title="Prof Devel Engineering" id="catalog-subject-PDEN">Prof Devel Engineering</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PDIT" title="Professional Development" id="catalog-subject-PDIT">Professional Development</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PRST" title="Professional Studies" id="catalog-subject-PRST">Professional Studies</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=PSYC" title="Psychology" id="catalog-subject-PSYC">Psychology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=DI" title="Radiology" id="catalog-subject-DI">Radiology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=REL" title="Religion" id="catalog-subject-REL">Religion</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=NRS" title="Research" id="catalog-subject-NRS">Research</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=RS" title="Research- Chiropractic" id="catalog-subject-RS">Research- Chiropractic</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=RSPTH" title="Respiratory Therapy" id="catalog-subject-RSPTH">Respiratory Therapy</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=RETL" title="Retailing" id="catalog-subject-RETL">Retailing</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=XR" title="Roentgenology" id="catalog-subject-XR">Roentgenology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=RUSS" title="Russian" id="catalog-subject-RUSS">Russian</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=RUS" title="Russian" id="catalog-subject-RUS">Russian</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=SCI" title="Science" id="catalog-subject-SCI">Science</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=SOSC" title="Social Sciences" id="catalog-subject-SOSC">Social Sciences</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=SOC" title="Sociology" id="catalog-subject-SOC">Sociology</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=SPAN" title="Spanish" id="catalog-subject-SPAN">Spanish</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=SPMT" title="Sports Management" id="catalog-subject-SPMT">Sports Management</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=STAT" title="Statistics" id="catalog-subject-STAT">Statistics</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=TCMG" title="Technology Management" id="catalog-subject-TCMG">Technology Management</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=TMPD" title="Technology Management Phd" id="catalog-subject-TMPD">Technology Management Phd</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=TEXT" title="Textiles" id="catalog-subject-TEXT">Textiles</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=THA" title="Theatre" id="catalog-subject-THA">Theatre</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=AWB" title="Western Biomedicine" id="catalog-subject-AWB">Western Biomedicine</a>
    <a class="esg-list-group__item" data-bind="text: Description, attr: { 'href': searchUrl, 'title': Description, 'id': 'catalog-subject-'+Code() }, click: clickHandler" href="/Student/Student/Courses/Search?subjects=WREL" title="World Religions" id="catalog-subject-WREL">World Religions</a>
</section>
DEP;

function var_export_new($var, $indent = "")
{
    switch (gettype($var)) {
        case "string":
            return '"' . addcslashes($var, "\\\$\"\r\n\t\v\f") . '"';
        case "array":
            $indexed = array_keys($var) === range(0, count($var) - 1);
            $r = [];
            foreach ($var as $key => $value) {
                $r[] = "$indent    "
                    . ($indexed ? "" : var_export_new($key) . " => ")
                    . var_export_new($value, "$indent    ");
            }
            return "[\n" . implode(",\n", $r) . "\n" . $indent . "]";
        case "boolean":
            return $var ? "TRUE" : "FALSE";
        default:
            return var_export($var, true);
    }
}


            preg_match_all('/\?subjects=(\w*)" title="(.*)" id/', $departments, $matches, PREG_SET_ORDER);

$fixed = [];

foreach ($matches as $match) {
    $fixed[] = [
        'name' => $match[2],
        'prefix' => $match[1],
    ];
}

echo '<pre>';

//file_put_contents('departments.php', "<?php\n\nreturn ".var_export_new($fixed));

//echo "<?php\n\nreturn ".var_export_new($fixed);
