<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;

class Catalog extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'semester',
        'year',
        'is_active',
    ];

    protected static function boot()
    {
//        static::deleting(function($catalog) {
//            $catalog->
//        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function courseSections()
    {
        return $this->hasMany(CourseSection::class);
    }

    public function scopeActive(Builder $query)
    {
        $query->where('is_active', 1);
    }
}
