<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Message extends Model
{
    use HasFactory;

    protected $casts = [
        'read_at' => 'datetime',
    ];

    protected $fillable = [
        'conversation_id',
        'user_id',
        'content',
    ];

    protected static function boot()
    {
        static::created(function (Message $message) {
            $message->conversation()->update([
                'message_count' => DB::raw('message_count + 1'),
//                'has_unread'    => 1,
            ]);
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function conversation()
    {
        return $this->belongsTo(Conversation::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
